repos:
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      name: Flake8

- repo: https://github.com/PyCQA/isort
  rev: 5.13.0
  hooks:
    - id: isort
      name: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      exclude: is_it_ok.sh
    - id: end-of-file-fixer
